# Generated by Django 3.1.2 on 2020-10-31 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbd', models.CharField(max_length=100, verbose_name='商圈助力链接')),
                ('help_num', models.IntegerField(default=0, verbose_name='被助力次数')),
                ('be_helped_num', models.IntegerField(default=0, verbose_name='被助力次数')),
                ('cbd_help_num', models.IntegerField(default=0, verbose_name='商圈助力次数')),
                ('cbd_be_helped_num', models.IntegerField(default=0, verbose_name='商圈被助力次数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_help', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
