# Generated by Django 3.1.2 on 2020-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='help_type',
            field=models.IntegerField(),
        ),
    ]
