# Generated by Django 3.1.2 on 2020-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201102_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='cbd',
            field=models.CharField(default='', max_length=100, verbose_name='商圈助力链接'),
        ),
    ]
