# Generated by Django 3.1.2 on 2020-11-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201102_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='cbd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='商圈助力链接'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='help_num',
            field=models.IntegerField(default=0, verbose_name='助力次数'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='star',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='星店长助力链接'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='tm',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='时光机助力链接'),
        ),
    ]
